import createFetchClient from 'openapi-fetch'
import createClient from 'openapi-react-query'
import { useState } from 'react'
import type { paths } from '../.schema/openapi.d' // auto-generated by openapi-typescript, see fastapi code in main.py
import './App.css'
import viteLogo from '/vite.svg'
import reactLogo from './assets/react.svg'

const fetchClient = createFetchClient<paths>({
  baseUrl: 'http://localhost:8000/',
})
const $api = createClient(fetchClient)

function App() {
  const { mutate, data, isPending } = $api.useMutation('get', '/')
  const [count, setCount] = useState(0)

  return (
    <>
      <div>
        <a href="https://vite.dev" target="_blank" rel="noreferrer">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank" rel="noreferrer">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>FastAPI + ReactQuery = Typed</h1>
      <div className="card">
        <pre className="code">
          {data ? (
            <code>{JSON.stringify(data, null, 2)}</code>
          ) : isPending ? (
            'Fetching...'
          ) : (
            'No data, click button to fetch...'
          )}
        </pre>

        <button type="button" onClick={() => mutate({})} disabled={isPending}>
          {isPending ? 'Fetching...' : 'Fetch api data'}
        </button>
      </div>
      <div className="card">
        <button type="button" onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </>
  )
}

export default App
